# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

env:
  aws-region: us-east-1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform_plan:
    name: terraform
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      - name: setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7 
        
      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          Aws-region: ${{env.aws-region}}

      # Runs command using the runners shell
      - name: terraform init
        # uses: hashicorp/terraform-github-actions/init@v0.4.0
        run: terraform init
      # - name: terraform Validate
      #   uses: hashicorp/terraform-github-actions/validate@v0.3.7
      - name: terraform plan
        run: terraform plan
      - name: terraform Apply
        run: terraform apply -auto-approve
        # uses: hashicorp/terraform-github-actions/apply@v0.4.0
        